---
title: "selecting human gut samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(curatedMetagenomicData)
set.seed(42)
```

Checking how many samples of each age_category are westernized or non westernized

```{r}
combined_metadata %>% select(c(age_category, non_westernized)) %>% table() %>% as.matrix()
```


Selecting randomly 100 samples of each class
```{r}
westernized = combined_metadata %>% filter(body_site == 'stool' & age_category != 'newborn' & non_westernized == 'no') %>% sample_n(100)
non_westernized = combined_metadata %>% filter(body_site == 'stool' & age_category != 'newborn' & non_westernized == 'yes') %>% sample_n(100)
```

```{r}
westernized_studies = westernized %>% select(dataset_name) %>% .[[1]] %>% paste0(".metaphlan_bugs_list.stool")
non_westernized_studies = non_westernized %>% select(dataset_name) %>% .[[1]] %>% paste0(".metaphlan_bugs_list.stool")
```


```{r}
esl_west = curatedMetagenomicData(westernized_studies, dryrun = FALSE, counts = TRUE)
esl_non_west = curatedMetagenomicData(non_westernized_studies, dryrun = FALSE, counts = TRUE)
```


```{r}
eset_west = mergeData(esl_west)
eset_west_pdata = pData(eset_west) %>% as.tibble(rownames='rowname') %>% filter(non_westernized=='no')
eset_west_exprs = exprs(eset_west)[,eset_west_pdata$rowname]
eset_non_west = mergeData(esl_non_west)
eset_non_west_pdata = pData(eset_non_west) %>% as.tibble(rownames='rowname') %>% filter(non_westernized=='yes')
eset_non_west_exprs = exprs(eset_non_west)[,eset_non_west_pdata$rowname]
```


```{r}
write.csv(as.data.frame(eset_west_exprs), "westernized_count.csv")
write.csv(as.data.frame(eset_non_west_exprs), "non_westernized_count.csv")
write.csv(as.data.frame(eset_west_pdata), "westernized_metadata.csv")
write.csv(as.data.frame(eset_non_west_pdata), "non_westernized_metadata.csv")
```

```{r}
getwd()
```


